### ISSUE TITLE
CI is intermittently timing out on master

### ISSUE THREAD

**Issue by DilumAluthge** [chriselrod/ThreadingUtilities.jl#3]

**Comment by DilumAluthge** [comment]
Some of the jobs are failing, and others are timing out.

**Comment by chriselrod** [comment]
I'll add counters and `@assert`s to the while loops to try and find out where it's getting suck.

**Comment by chriselrod** [comment]
It looks like the timeouts may be a Windows problem.

**Comment by DilumAluthge** [comment]
CI is now passing on master, so I'll close this.

**Comment by DilumAluthge** [comment]
Reopening this.

**Comment by chriselrod** [comment]
Failure on 1.5 and 1.6:
https://github.com/chriselrod/ThreadingUtilities.jl/runs/1725829471?check_suite_focus=true

**Comment by DilumAluthge** [comment]
One timeout is on Linux, and one timeout is on macOS. So presumably it's not an OS-related bug.

**Comment by DilumAluthge** [comment]
Maybe run some kind of loop on your local machines?

E.g. 

```julia
import Pkg

while true
    Pkg.test("ThreadingUtilities")
end
```

You could do the loop in `bash` instead of Julia.

And maybe run all of that inside of `rr`? So that when you finally catch a timeout, you can replay it?

**Comment by DilumAluthge** [comment]
Here's another failure, on macOS: https://github.com/chriselrod/ThreadingUtilities.jl/runs/1726038737

**Comment by DilumAluthge** [comment]
Got another failure, this time on Linux: https://github.com/chriselrod/ThreadingUtilities.jl/runs/1726061663

**Comment by DilumAluthge** [comment]
Here's a failing job: https://github.com/chriselrod/ThreadingUtilities.jl/runs/1726160608

And here's a passing job on the same commit: https://github.com/chriselrod/ThreadingUtilities.jl/runs/1726160653

Log for the failing job:
```
┌ Info: 
└   Threads.nthreads() = 5
┌ Info: 
└   Sys.CPU_THREADS = 2
┌ Info: 
└   VectorizationBase.NUM_CORES = 2
┌ Info: 
└   length(ThreadingUtilities.TASKS) = 1
[ Info: Beginning to run the ThreadingUtilities test suite
Test Summary: | Pass  Total
THREADPOOL    |    4      4
  0.468356 seconds (741.25 k allocations: 41.449 MiB, 19.53% gc time, 99.50% compilation time)
Test Summary: | Pass  Total
Internals     |    3      3
  0.004237 seconds (266 allocations: 32.570 KiB, 92.60% compilation time)
Skipping Base.active_repl
Skipping Base.active_repl_backend
Skipping Base.Filesystem.JL_O_RANDOM
Skipping Base.Filesystem.JL_O_SEQUENTIAL
Skipping Base.Filesystem.JL_O_SHORT_LIVED
Skipping Base.Filesystem.JL_O_TEMPORARY
Skipping Base.BinaryPlatforms.compiler_abi
Skipping Base.active_repl
Skipping Base.active_repl_backend
Skipping Base.Filesystem.JL_O_RANDOM
Skipping Base.Filesystem.JL_O_SEQUENTIAL
Skipping Base.Filesystem.JL_O_SHORT_LIVED
Skipping Base.Filesystem.JL_O_TEMPORARY
Skipping Base.BinaryPlatforms.compiler_abi
Error: The operation was canceled.
```

Log for the passing job:
```
┌ Info: 
└   Threads.nthreads() = 5
┌ Info: 
└   Sys.CPU_THREADS = 3
┌ Info: 
└   VectorizationBase.NUM_CORES = 3
┌ Info: 
└   length(ThreadingUtilities.TASKS) = 2
[ Info: Beginning to run the ThreadingUtilities test suite
Test Summary: | Pass  Total
THREADPOOL    |    4      4
  0.299020 seconds (741.38 k allocations: 41.456 MiB, 2.36% gc time, 98.06% compilation time)
Test Summary: | Pass  Total
Internals     |    3      3
  0.004492 seconds (256 allocations: 32.102 KiB, 80.02% compilation time)
Skipping Base.active_repl
Skipping Base.active_repl_backend
Skipping Base.Filesystem.JL_O_RANDOM
Skipping Base.Filesystem.JL_O_SEQUENTIAL
Skipping Base.Filesystem.JL_O_SHORT_LIVED
Skipping Base.Filesystem.JL_O_TEMPORARY
Skipping Base.BinaryPlatforms.compiler_abi
Skipping Base.active_repl
Skipping Base.active_repl_backend
Skipping Base.Filesystem.JL_O_RANDOM
Skipping Base.Filesystem.JL_O_SEQUENTIAL
Skipping Base.Filesystem.JL_O_SHORT_LIVED
Skipping Base.Filesystem.JL_O_TEMPORARY
Skipping Base.BinaryPlatforms.compiler_abi
Test Summary: | Pass  Total
Aqua          |    7      7
 10.775370 seconds (2.96 M allocations: 175.123 MiB, 0.57% gc time, 19.82% compilation time)
[ Info: foo 1
[ Info: foo 2
[ Info: foo 3
[ Info: foo 4
[ Info: foo 5
[ Info: foo 6
[ Info: foo 7
Test Summary:         | Pass  Total
ThreadingUtilities.jl |    2      2
[ Info: Finished running the ThreadingUtilities test suite
     Testing ThreadingUtilities tests passed 
```

**Comment by DilumAluthge** [comment]
This is where it gets really interesting. From my PR that triggered these jobs:

https://github.com/chriselrod/ThreadingUtilities.jl/blob/7db38832f2c335232e9e0d568eb8a8d52aa4189f/test/runtests.jl#L78-L85

**Comment by DilumAluthge** [comment]
It never got to line 83 (the `@info "foo 1" `) line.

So this implies that the timeout... is actually happening inside the `Aqua.test_all(ThreadingUtilities) `.

**Comment by DilumAluthge** [comment]
It might not be Aqua. https://github.com/chriselrod/ThreadingUtilities.jl/runs/1726363081?check_suite_focus=true

**Comment by chriselrod** [comment]
I suspect the timeout is in `__init__()` then.

**Comment by DilumAluthge** [comment]
Me too. I'm particularly suspicious of that `pause()` inside a while loop.

**Comment by chriselrod** [comment]
`pause` only takes a few nanoseconds.

**Comment by DilumAluthge** [comment]
Yeah but what if the condition in the while loop never evaluates to false?

**Comment by chriselrod** [comment]
```julia
julia> using VectorizationBase

julia> @code_native syntax=:intel pause()
        .text
; ┌ @ VectorizationBase.jl:317 within `pause'
        pause
        ret
        nop     word ptr cs:[rax + rax]
; └
```
`pause` is an assembly instruction that hints to the CPU that you're inside a spin loop, waiting for another thread to do something.

Yes, I suspect that the condition never evaluates to `false`.

**Comment by DilumAluthge** [comment]
In this job, we never successfully import the package, which smells like an init problem: https://github.com/chriselrod/ThreadingUtilities.jl/runs/1726922690

**Comment by chriselrod** [comment]
What is supposed to happen:
```julia
        m = THREADPOOL[tid]
        GC.@preserve m _atomic_min!(pointer(m), SPIN) # set to SPIN
```
We set it to `SPIN`.
We then wake up the thread:
```julia
        t = Task(m); t.sticky = true # create and pin
        # set to tid, we have tasks 2...nthread, from 1-based ind perspective
        ccall(:jl_set_task_tid, Cvoid, (Any, Cint), t, tid % Cint)
        TASKS[tid] = t
        wake_thread!(tid) # task should immediately sleep
```
When awake, it runs:
```julia
function (tt::ThreadTask)()
    p = pointer(tt)
    memory = tt.memory
    max_wait = 1 << 20
    wait_counter = max_wait
    GC.@preserve memory begin
        while true
            if _atomic_cas_cmp!(p, TASK, LOCK)
                _call(p)
                @assert _atomic_cas_cmp!(p, LOCK, SPIN)
                wait_counter = 0
                continue
            end
            pause()
            if (wait_counter += 1) > max_wait
                wait_counter = 0
                if _atomic_cas_cmp!(p, SPIN, WAIT)
                    wait()
                    _call(p)
                    @assert _atomic_cas_cmp!(p, LOCK, SPIN)
                end
            end
        end
    end
end
```
It should be set to `SPIN` (because we just set it to `SPIN`), and then immediately the `wait_counter` should be greater than `max_wait`, so that ` if _atomic_cas_cmp!(p, SPIN, WAIT)` is `true`, and it gets set to `WAIT`.
Then of course
```julia
        while !_atomic_cas_cmp!(pointer(m), WAIT, WAIT)
            pause()
        end
```
`_atomic_cas_cmp!(pointer(m), WAIT, WAIT)` is true, and thus `!` the condition is false and the loop is done.

**Comment by DilumAluthge** [comment]
Check out the logs for https://github.com/chriselrod/ThreadingUtilities.jl/runs/1726933020

This job ran on commit https://github.com/chriselrod/ThreadingUtilities.jl/pull/12/commits/b9054e071415abb19848ddf51ae10c322d382cd7

**Comment by chriselrod** [comment]
Could you add `@show _atomic_max!(p, SPIN)`?

**Comment by DilumAluthge** [comment]
Like this? https://github.com/DilumAluthge/ThreadingUtilities.jl/commit/6fb0ecb42756af66477a3d770c74915b7a2da1f8

**Comment by chriselrod** [comment]
Yes. It'd also help to know which loop it is in at the time, so maybe `@show @__LINE__, _atomic_max!(p, SPIN)`

**Comment by DilumAluthge** [comment]
I'm about to leave the house- want to push those changes to my branch? You should be able to.

**Comment by chriselrod** [comment]
Okay, thanks for all your help so far.
I can already see here:
```julia
 [ Info: threadtask beginning to pause...
ERROR: [ Info: threadtask finished pausing
InitError: KeyError: key 0x9b3e6abc04ee57a9 not found
```
That the current state is uninitialized junk, rather than one of the `enum` values.

**Comment by DilumAluthge** [comment]
On master: https://github.com/chriselrod/ThreadingUtilities.jl/runs/1727659327

**Comment by chriselrod** [comment]
Everything should be fixed as of the "add utils.jl" commit. I'll reopen this if we see more intermittent timeouts.
